apiVersion: v1
kind: Service
metadata:
  name: oracle23ai
  namespace: oracle
  annotations:
    metallb.universe.tf/address-pool: oracle-pool
spec:
  selector:
    app: oracle23ai
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
