apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle23ai
  namespace: oracle
  labels:
    app: oracle23ai
spec:
  selector:
    matchLabels:
      app: oracle23ai
  strategy:
    type: Recreate
  revisionHistoryLimit: 0 # Removes old ReplicaSets
  template:
    metadata:
      labels:
        app: oracle23ai
    spec:
      containers:
      - image: container-registry.oracle.com/database/free:latest
        name: oracle23ai
        env:
        - name: ORACLE_PWD
          valueFrom:
            secretKeyRef:
              name: oracle-pass
              key: password
        - name: ORACLE_PDB
          value: "FREEPDB1"
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        - name: ENABLE_ARCHIVELOG
          value: "false"
        - name: ENABLE_FORCE_LOGGING
          value: "false"
        ports:
        - containerPort: 1521
          name: oracle
        volumeMounts:
        - name: oracle23ai-pv
          mountPath: /opt/oracle/oradata
      volumes:
      - name: oracle23ai-pv
        persistentVolumeClaim:
          claimName: oracle23ai-pv-claim
