apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle23ai-pv-claim
  namespace: oracle
  labels:
    app: oracle23ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
